#!/bin/bash
gnuplot -persist <<-EOFMarker
	set title "File Types"
	set terminal png
	set autoscale
	set output "FileTypes.png"
	set style data histograms
	set style fill solid 1.00 border -1
	set yrange [0:10<*]
        set xtics center
        set grid
	plot "output.txt" using 1:xtic(2) title "File Types"
EOFMarker